// <auto-generated />
using System;
using Makitools.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Makitools.Infrastructure.Migrations
{
    [DbContext(typeof(MakitoolsDbContext))]
    [Migration("20260630213356_AddColumnCondicionesPago")]
    partial class AddColumnCondicionesPago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Makitools.Domain.Entities.Almacen.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__A3C02A105610846F");

                    b.ToTable("Categoria", "Almacen");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Almacen.Kardex", b =>
                {
                    b.Property<long>("IdKardex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdKardex"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("FechaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdReferencia")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NumeroGuia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SaldoFisico")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdKardex")
                        .HasName("PK__Kardex__BC1BA4009B903A6E");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "IdProducto", "FechaMovimiento" }, "IX_Kardex_Producto_Fecha")
                        .IsDescending(false, true);

                    b.ToTable("Kardex", "Almacen");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Almacen.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdMarca")
                        .HasName("PK__Marca__4076A887FA83B06B");

                    b.ToTable("Marca", "Almacen");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Almacen.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("CostoPromedio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RutaImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SKU");

                    b.Property<double?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__09889210B253E7C3");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdMarca");

                    b.HasIndex(new[] { "Nombre" }, "IX_Producto_Nombre");

                    b.HasIndex(new[] { "Sku" }, "IX_Producto_SKU");

                    b.HasIndex(new[] { "Sku" }, "UQ__Producto__CA1ECF0DE253D26A")
                        .IsUnique();

                    b.ToTable("Producto", "Almacen");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Compras.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<string>("CondicionesPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Registrado");

                    b.Property<DateTime?>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaEntregaEsperada")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("LugarEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroGuiaEntrada")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroOrdenCompra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Factura");

                    b.HasKey("IdCompra")
                        .HasName("PK__Compra__0A5CDB5C9C54687A");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "FechaCompra" }, "IX_Compra_FechaCompra")
                        .IsDescending();

                    b.ToTable("Compra", "Compras");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Compras.DetalleCompra", b =>
                {
                    b.Property<int>("IdDetalleCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleCompra"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdDetalleCompra")
                        .HasName("PK__DetalleC__E046CCBB45F7C0D2");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetalleCompra", "Compras");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Clave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__D5946642B3F6818C");

                    b.HasIndex(new[] { "NumeroDocumento" }, "IX_Cliente_NumDoc");

                    b.HasIndex(new[] { "Correo" }, "UQ__Cliente__60695A1943859169")
                        .IsUnique()
                        .HasFilter("[Correo] IS NOT NULL");

                    b.HasIndex(new[] { "NumeroDocumento" }, "UQ__Cliente__A42025881AE1C1D5")
                        .IsUnique();

                    b.ToTable("Cliente", "Maestros");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Departamento", b =>
                {
                    b.Property<string>("IdDepartamento")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdDepartamento")
                        .HasName("PK__Departam__787A433D9D57C0A5");

                    b.ToTable("Departamento", "Maestros");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Distrito", b =>
                {
                    b.Property<string>("IdDistrito")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IdProvincia")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.HasKey("IdDistrito")
                        .HasName("PK__Distrito__DE8EED59D1BC0A13");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Distrito", "Maestros");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RUC");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdProveedor")
                        .HasName("PK__Proveedo__E8B631AFEB64FA9E");

                    b.HasIndex(new[] { "Ruc" }, "UQ__Proveedo__CAF3326B39B00619")
                        .IsUnique();

                    b.ToTable("Proveedor", "Maestros");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Provincia", b =>
                {
                    b.Property<string>("IdProvincia")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IdDepartamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("IdProvincia")
                        .HasName("PK__Provinci__EED74455BF2E5689");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Provincia", "Maestros");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__2A49584C3F6DBABC");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Rol__75E3EFCFD6AF42AA")
                        .IsUnique();

                    b.ToTable("Rol", "Maestros");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Reestablecer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF9713007378");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuario__60695A1934903A4C")
                        .IsUnique();

                    b.ToTable("Usuario", "Maestros");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Ventas.Carrito", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrito"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdCarrito")
                        .HasName("PK__Carrito__8B4A618CAA24421C");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "IdCliente" }, "IX_Carrito_Cliente");

                    b.HasIndex(new[] { "IdCliente", "IdProducto" }, "UQ_Cliente_Producto")
                        .IsUnique();

                    b.ToTable("Carrito", "Ventas");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Ventas.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleVenta"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdDetalleVenta")
                        .HasName("PK__DetalleV__AAA5CEC2D634A448");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetalleVenta", "Ventas");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Ventas.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("AgenciaEnvio")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Completado");

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("IdDistrito")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("IGV");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroGuiaEnvio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroOperacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RutaVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Boleta");

                    b.HasKey("IdVenta")
                        .HasName("PK__Venta__BC1240BD126DE311");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDistrito");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "FechaVenta" }, "IX_Venta_FechaVenta")
                        .IsDescending();

                    b.ToTable("Venta", "Ventas");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Almacen.Kardex", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Almacen.Producto", "IdProductoNavigation")
                        .WithMany("Kardices")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Kardex__IdProduc__14270015");

                    b.HasOne("Makitools.Domain.Entities.Maestros.Usuario", "IdUsuarioNavigation")
                        .WithMany("Kardices")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Kardex__IdUsuari__151B244E");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Almacen.Producto", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Almacen.Categoria", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__Producto__IdCate__6E01572D");

                    b.HasOne("Makitools.Domain.Entities.Almacen.Marca", "IdMarcaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdMarca")
                        .IsRequired()
                        .HasConstraintName("FK__Producto__IdMarc__6EF57B66");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdMarcaNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Compras.Compra", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Maestros.Proveedor", "IdProveedorNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__IdProvee__75A278F5");

                    b.HasOne("Makitools.Domain.Entities.Maestros.Usuario", "IdUsuarioNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__IdUsuari__76969D2E");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Compras.DetalleCompra", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Compras.Compra", "IdCompraNavigation")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("IdCompra")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleCo__IdCom__7C4F7684");

                    b.HasOne("Makitools.Domain.Entities.Almacen.Producto", "IdProductoNavigation")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleCo__IdPro__7D439ABD");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Distrito", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Maestros.Provincia", "IdProvinciaNavigation")
                        .WithMany("Distritos")
                        .HasForeignKey("IdProvincia")
                        .IsRequired()
                        .HasConstraintName("FK__Distrito__IdProv__4E88ABD4");

                    b.Navigation("IdProvinciaNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Provincia", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Maestros.Departamento", "IdDepartamentoNavigation")
                        .WithMany("Provincia")
                        .HasForeignKey("IdDepartamento")
                        .IsRequired()
                        .HasConstraintName("FK__Provincia__IdDep__4BAC3F29");

                    b.Navigation("IdDepartamentoNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Usuario", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Maestros.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__IdRol__5629CD9C");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Ventas.Carrito", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Maestros.Cliente", "IdClienteNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__Carrito__IdClien__0F624AF8");

                    b.HasOne("Makitools.Domain.Entities.Almacen.Producto", "IdProductoNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Carrito__IdProdu__10566F31");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Ventas.DetalleVenta", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Almacen.Producto", "IdProductoNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleVe__IdPro__09A971A2");

                    b.HasOne("Makitools.Domain.Entities.Ventas.Venta", "IdVentaNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleVe__IdVen__08B54D69");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Ventas.Venta", b =>
                {
                    b.HasOne("Makitools.Domain.Entities.Maestros.Cliente", "IdClienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__Venta__IdCliente__01142BA1");

                    b.HasOne("Makitools.Domain.Entities.Maestros.Distrito", "IdDistritoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdDistrito")
                        .HasConstraintName("FK__Venta__IdDistrit__02FC7413");

                    b.HasOne("Makitools.Domain.Entities.Maestros.Usuario", "IdUsuarioNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Venta__IdUsuario__02084FDA");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDistritoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Almacen.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Almacen.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Almacen.Producto", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("DetalleCompras");

                    b.Navigation("DetalleVenta");

                    b.Navigation("Kardices");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Compras.Compra", b =>
                {
                    b.Navigation("DetalleCompras");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Cliente", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Departamento", b =>
                {
                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Distrito", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Provincia", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Maestros.Usuario", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Kardices");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Makitools.Domain.Entities.Ventas.Venta", b =>
                {
                    b.Navigation("DetalleVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
